config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'files#index'
  resources :files, only: %i[show create destroy], as: :file_infos
  resources :download, only: %i[show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_content.rb
# frozen_string_literal: true

class FileContent < ApplicationRecord
  belongs_to :file_info
end

app/models/file_info.rb
# frozen_string_literal: true

class FileInfo < ApplicationRecord
  include Hashid::Rails

  has_secure_password
  has_one :file_content, dependent: :destroy

  validate :validate_file

  scope :public_file_infos, -> {
    where(
      'private = :private AND (expiration IS NULL OR expiration >= :expiration)',
      private: false,
      expiration: Time.current
    ).order(:created_at).reverse_order
  }

  def file=(file)
    self.name = file.original_filename

    io = file.to_io
    io.set_encoding(Encoding::ASCII_8BIT, Encoding::ASCII_8BIT)
    content = io.read

    self.content_size = content.size
    self.file_content = FileContent.new
    file_content.content = content
  end

  def outdated?
    return false unless expiration
    expiration < Time.current
  end

  private def validate_file
    if name.blank? || content_size.blank?
      errors.add(:file, "can't be empty")
      return
    end

    if content_size >= 500.kilobytes
      errors.add(:file, 'is too big')
      return
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/file_info_concern.rb
# frozen_string_literal: true

module FileInfoConcern
  extend ActiveSupport::Concern

  included do
    before_action :set_file_info, only: %i[show destroy]
  end

  private def set_file_info
    @file_info = FileInfo.find_by_hashid!(params[:id])
    if @file_info.outdated?
      raise ActiveRecord::RecordNotFound, "#{params[:id]} is outdated"
    end
  end
end

app/controllers/download_controller.rb
# frozen_string_literal: true

class DownloadController < ApplicationController
  include FileInfoConcern

  def show
    @file_content = @file_info.file_content
    send_data @file_content.content, filename: @file_info.name, disposition: :inline
  end
end

app/controllers/files_controller.rb
# frozen_string_literal: true

class FilesController < ApplicationController
  include FileInfoConcern

  def index
    @file_infos = FileInfo.public_file_infos
    @file_info = FileInfo.new
  end

  def show; end

  def create
    @file_info = FileInfo.new(file_info_params)

    if @file_info.save
      redirect_to @file_info, notice: 'Uploading OK'
    else
      render status: :bad_request
    end
  end

  def destroy
    password = params[:password]

    if @file_info.authenticate(password)
      @file_info.destroy!
      redirect_to({ action: :index }, notice: 'Deleting OK')
    else
      redirect_to @file_info, alert: 'Deleting Failed (Invalid Password)'
    end
  end

  private def file_info_params
    params.require(:file_info).permit(
      :file,
      :private,
      :expiration,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/files/_form.html.haml
= form_with model: file_info, html: {class: "col s12"}, local: false do |form|
  - if file_info.errors.present?
    - file_info.errors.full_messages.each do |message|
      %div.row
        %div.col.s12
          %div.card-panel.red.lighten-2
            %span.white-text= message
  %div.row
    %div.file-field.input-field.col.s12
      %div.btn
        = form.file_field :file, id: :file_info_file
        = form.label :file, "File"
      %div.file-path-wrapper
        = form.text_field :file, name: nil, class: "file-path validate"
  %div.row
    %div.input-field.col.s6
      = form.password_field :password, class: "validate", id: :file_info_password
      = form.label :password, "Password to Delete"
    %div.input-field.col.s6
      = form.password_field :password_confirmation, class: "validate", id: :file_info_password_confirmation
      = form.label :password_confirmation, "Password (Confirmation)"
  %div.row
    %div.input-field.col.s12
      = form.text_field :expiration, class: "datepicker", id: :file_info_expiration
      = form.label :expiration, "Expiration Date (Optional)"
  %div.row
    %div.col.s3
      = form.submit "Upload", class: "waves-effect waves-light btn"
    %div.col.s3
      = form.check_box :private, id: :file_info_private
      = form.label :private, "Private Mode"

app/views/files/create.html.haml
%div.row
  %div.col.s12
    %h3 Upload a New File
%div.row
  = render partial: "form", locals: {file_info: @file_info}

app/views/files/index.html.haml
- if flash[:notice].present?
  %div.row
    %div.col.s12
      %div.card-panel.teal.lighten-2
        %span.white-text= flash[:notice]
%div.row
  %div.col.s12
    %h3 File List
  %col.s12
    %ul.collection
      - @file_infos.each do |file_info|
        %li.collection-item= link_to file_info.name, file_info
%div.row
  %div.col.s12
    %h3 Upload a New File
%div.row
  = render partial: "form", locals: {file_info: @file_info}

app/views/files/show.html.haml
- if flash[:notice].present?
  %div.row
    %div.col.s12
      %div.card-panel.teal.lighten-2
        %span.white-text= flash[:notice]
- if flash[:alert].present?
  %div.row
    %div.col.s12
      %div.card-panel.red.lighten-2
        %span.white-text= flash[:alert]

%div.row
  %div.col.s12
    %h3
      = @file_info.name
      = link_to "Download", download_path(@file_info), class: "waves-effect waves-light btn"

%div.row
  %div.col.s12
    %h4 File Information
%div.row
  %div.col.s12
    %table.responsive-table
      %thead
        %tr
          %th Name
          %th Size
          %th Created At
      %tbody
        %tr
          %td= @file_info.name
          %td= number_to_human_size(@file_info.content_size)
          %td= @file_info.created_at


%div.row
  %div.col.s12
    %h4 Delete This File
%div.row
  = form_with model: @file_info, method: :delete, html: {class: "col s12"}, local: true do |form|
    %div.row
      %div.input-field.col.s8
        = label_tag :password, "Password"
        = password_field_tag :password
      %div.col.s4
        = form.submit "Delete", class: "waves-effect waves-light btn-large"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Upload2
    = csrf_meta_tags
    = javascript_pack_tag("application")
    = stylesheet_pack_tag("application")
  %body
    %nav
      %div.nav-wrapper
        %a.brand-logo.center{href: root_url} The File Uploader
    %div.container
      = yield